apiVersion: v1
kind: ConfigMap
metadata:
  name: accumulo-proxy-configmap
  labels:
    app: {{ template "accumulo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  log4j2.properties: |
     status = info
     dest = err
     name = AccumuloDefaultLoggingProperties
     monitorInterval = 30

     appender.console.type = Console
     appender.console.name = STDERR
     appender.console.target = SYSTEM_ERR
     appender.console.layout.type = PatternLayout
     appender.console.layout.pattern = %style{%d{ISO8601}}{dim,cyan} %style{[}{red}%style{%C}{dim,blue}%style{]}{red} %highlight{%-5p}%style{:}{red} %m%n

     logger.shellaudit.name = org.apache.accumulo.shell.Shell.audit
     logger.shellaudit.level = warn

     logger.zookeeper.name = org.apache.zookeeper
     logger.zookeeper.level = error

     rootLogger.level = debug
     rootLogger.appenderRef.console.ref = STDERR

  accumulo-client.properties: |
    instance.name={{ .Values.proxy.instance_name }}
    instance.zookeepers={{ .Values.zookeeper.host }}
    #instance.zookeepers.timeout=30s
    auth.type=password
    auth.principal={{ .Values.proxy.username }}
    auth.token={{ .Values.proxy.passwd }}

  proxy.properties: |
    ###############################
    ## Accumulo Proxy configuration
    ###############################
    port={{ .Values.proxy.port }}
    sharedSecret=sharedSecret
    useMiniAccumulo=false
    protocolFactory=org.apache.thrift.protocol.TCompactProtocol$Factory
    tokenClass=org.apache.accumulo.core.client.security.tokens.PasswordToken
    maxFrameSize=16M
    ################################
    ## Accumulo client configuration
    ################################
    auth.type=password
    auth.principal={{ .Values.proxy.username }}
    auth.token={{ .Values.proxy.passwd }}
    instance.name={{ .Values.proxy.instance_name }}
    instance.zookeepers={{ .Values.zookeeper.host }}
