{{- $fullName := .Values.proxy.name }}
{{- $replicaCount := .Values.proxy.replicas | int }}
{{- $root := . }}

{{- range $i, $e := until $replicaCount }}
{{- $targetPod := printf "%s-proxy-%d" (printf "%s" $fullName) $i }}
{{- $_ := set $ "targetPod" $targetPod }}
apiVersion: v1
kind: Service
metadata:
    name: {{ $targetPod }}
    labels:
        app: {{ $fullName }}
        chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
        release: {{ $root.Release.Name }}
        heritage: {{ $root.Release.Service }}
        pod: {{ $targetPod }}
        component: {{ $fullName }}-proxy
spec:
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
      - name: proxy-server
        protocol: TCP
        port: {{ $root.Values.proxy.port }}
        targetPort: {{ $root.Values.proxy.port }}
    selector:
        statefulset.kubernetes.io/pod-name: {{ $targetPod }}
    sessionAffinity: None
status:
    loadBalancer: {}
---
{{- end }}
